// <auto-generated />
using System;
using EmployeeLeaveAndAttendanceManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeLeaveAndAttendanceManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250619054440_issue16Mig")]
    partial class issue16Mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClockOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("WorkHours")
                        .HasColumnType("time");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.AttendanceReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("Absenteeism")
                        .HasColumnType("int");

                    b.Property<int>("DateRange")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("TotalAttendance")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AttendanceReports");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.LeaveBalance", b =>
                {
                    b.Property<int>("LeaveBalanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveBalanceID"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaveBalanceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaveID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Shift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.SwapShiftRequest", b =>
                {
                    b.Property<int>("SwapShiftRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SwapShiftRequestID"));

                    b.Property<int>("FromShiftID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestingEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SwapShiftRequestID");

                    b.ToTable("SwapShiftRequests");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Attendance", b =>
                {
                    b.HasOne("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.AttendanceReport", b =>
                {
                    b.HasOne("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Employee", "Employee")
                        .WithMany("AttendanceReports")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.LeaveBalance", b =>
                {
                    b.HasOne("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.LeaveRequest", b =>
                {
                    b.HasOne("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Shift", b =>
                {
                    b.HasOne("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeLeaveAndAttendanceManagementSystem.Models.Domain.Employee", b =>
                {
                    b.Navigation("AttendanceReports");

                    b.Navigation("Attendances");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
